version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: developer
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      # Mount the workspace
      - ../..:/workspaces:cached
      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Persist extensions
      - vscode-extensions:/home/developer/.vscode-server/extensions
      # Persist shell history
      - zsh-history:/home/developer/.zsh_history
      # Persist npm/pnpm cache
      - pnpm-store:/home/developer/.local/share/pnpm/store

    # Keep container running
    command: sleep infinity

    # Use host network mode for better performance
    network_mode: host

    # Add capabilities for better debugging
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN

    # Security options
    security_opt:
      - seccomp:unconfined

    # Environment variables
    environment:
      - NODE_ENV=development
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pocket_console
      - REDIS_HOST=localhost
      - REDIS_PORT=6379

  # PostgreSQL database
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pocket_console
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Adminer for database management
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  postgres-data:
  redis-data:
  vscode-extensions:
  zsh-history:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/.zsh_history_devcontainer
  pnpm-store:
